### ISSUE TITLE
maybe Exercise 2.23  is not correct

### ISSUE THREAD

**Issue by ifgladlee** [Mooophy/Cpp-Primer#112]
even though  `if(p)` returns `true`, we cannot confirm that `p` points to a valid  object.
eg. if `p` points a location one past the end of some object. `if(p)` also returns `true`.

So I think we can't determine whether a point points a valid object.

**Comment by Mooophy** [comment]
Agree.
Below is copied from section 2.3.2, CP.
>Like other built-in types, pointers defined at block scope have undefined value if they are not initialized.
So even `if(p)` returns `true`, what `p` is pointing to is undefined.
Summon @pezy

**Comment by pezy** [comment]
Agree
