### ISSUE TITLE
Exercise 2.29

### ISSUE THREAD

**Issue by ifgladlee** [Mooophy/Cpp-Primer#113]
*Exercise 2.29* 
`(e) p2 = p1;` 
I think it's illegal, because p2 is a const pointer, so we can't assign a value to it.

**Comment by ifgladlee** [comment]
I have fixed it and commit a pull request

**Comment by wallcwr** [comment]
p2 = p1;    // illegal. p2 is a const pointer.
ic = *p3;   // illegal. ic is a const int.
I think that two answers are legal,not illegal,beacuse I can run them in TMD gcc-4.92
