### ISSUE TITLE
in ex8_13.cpp , isnumber can't be found !

### ISSUE THREAD

**Issue by mudongliang** [Mooophy/Cpp-Primer#115]
I can't compile this file , the reported is "isnumber function can't be found !"

**Comment by Mooophy** [comment]
@pezy 
Seems [these lines] has a little problem:
```cpp
bool valid(const string& str)
{
    return isnumber(str[0]); // here
}
``` 
Isn't it `std::isdigit`?

**Comment by mudongliang** [comment]
Actually , it's content is a >= '0' and a <='9' ! But I don't know the meaning of the author!

**Comment by Mooophy** [comment]
Summon @pezy  :walking:

**Comment by pezy** [comment]
>Isn't it std::isdigit?

Yes, but any guys test the codes by gcc4.9 or clang ? It can pass the compile.

**Comment by Mooophy** [comment]
really? Hold on. I'm gonna test it on 4.9.

**Comment by Mooophy** [comment]
I tried g++4.9 and clang 3.4, both failed.
Since on linux the default standard library is`gcc`'s `libstdc++` rather than `clang` 's `libc++`.
I guess you are using an Mac where `libc++` is default c++ library.
 Perhaps `isnumber` is defined in `libc++`

**Comment by pezy** [comment]
Maybe you are right. isdigit is more better.

**Comment by mudongliang** [comment]
I'm using the gcc version 4.8.

**Comment by Mooophy** [comment]
Nothing about compiler. I guess `isnumber` is an extension provided by `libc++`. 
@mudongliang

**Comment by Mooophy** [comment]
Ordinarily `libc++` is not provided on Linux.

**Comment by mudongliang** [comment]
I suggest that using the Cross-platform functions is good !

**Comment by pezy** [comment]
@Mooophy Could you please help me to correct it ?  (AFK)

**Comment by Mooophy** [comment]
No problem.
I'm gonna fix it latter on. AFK as well :smile:

**Comment by mudongliang** [comment]
I will close this issue !
