### ISSUE TITLE
 ex11_9_10.cpp can't be successfully compiled !

### ISSUE THREAD

**Issue by mudongliang** [Mooophy/Cpp-Primer#117]
![image](https://cloud.githubusercontent.com/assets/6214861/5594561/e64402fa-928c-11e4-91ab-ecf122f99841.png)

**Comment by Mooophy** [comment]
Exactly!
Because ex11.10 is trying to show an illegal syntax. The following is the description:
```haskell
//! Exercise 11.10:
//! Could we define a map from vector<int>::iterator
//! to int? What about from list<int>::iterator to int?
//! In each case, if not, why not?
```

**Comment by mudongliang** [comment]
OK , I got it ! I ignored it in my submission!

**Comment by Mooophy** [comment]
Cool.
