### ISSUE TITLE
13.57能不能详细解释一下呢

### ISSUE THREAD

**Issue by dangfeng** [Mooophy/Cpp-Primer#122]
能不能详细的解释一下练习13.57呢？

**Comment by Mooophy** [comment]
Can you tell me where did you have problem to understand?
e.g...Do you understand the exercise 13.56?

**Comment by Mooophy** [comment]
Hi~ @dangfeng 
To fully understand what's going on here, several syntax need to grasp, which are:
1 Lvalue,Rvalue
2 Lvalue reference, Rvalue reference
3 move semantics
4 reference qualifiers for function members
5 recursion
6 `this` pointer 

Can you give a little bit more information as to which part you want to discuss in detail?

**Comment by dangfeng** [comment]
Foo(*this).sorted()为什么会调用右值的版本呢？Foo(*this)和Foo ret(*this)有什么区别吗？

**Comment by dangfeng** [comment]
明白了。谢谢你！

**Comment by Mooophy** [comment]
No worries.
