### ISSUE TITLE
ex7_32.h中能不能把Window_mgr和Screen类拆分到两个文件中，clear是Window_mgr的成员，是Screen的友元？

### ISSUE THREAD

**Issue by qinf** [Mooophy/Cpp-Primer#123]
ex7_32.h为啥写到一个文件中？写到两个文件中不是更合理吗？我写到两个文件中但是一直出错！！

**Comment by pezy** [comment]
写到一个文件中，是因为两个类总**放到一起讲**，**关系比较密切**，且都**非常短小**，也为了更精简吧。

但你如果要分别写到两个头文件中，当然也是可以的。如果出错，能否提供错误提示呢？

**Comment by qinf** [comment]
@pezy 感谢 ![image](https://cloud.githubusercontent.com/assets/1277293/5658190/9e338886-9738-11e4-8fc8-4a458ffb4b35.png)
