### ISSUE TITLE
ex11_23.cpp can't be successfully compiled !

### ISSUE THREAD

**Issue by PoetLiu** [Mooophy/Cpp-Primer#130]
![image](https://cloud.githubusercontent.com/assets/8433498/5834692/4612dfd6-a19b-11e4-9b36-d59dfbcd556f.png)

**Comment by pezy** [comment]
your gcc version is ?

**Comment by PoetLiu** [comment]
Target: i486-linux-gnu
gcc version 4.7.2 (Debian 4.7.2-5)

**Comment by pezy** [comment]
@PoetLiu 

It's clear that your gcc version can't support all the feature of c++11. In this case, `emplace` isn't implemented in gcc 4.7.2. (see http://stackoverflow.com/questions/15812276/stdset-has-no-member-emplace)

**Comment by PoetLiu** [comment]
It's seems like that . 
Thx.
