### ISSUE TITLE
Header File In Ch13

### ISSUE THREAD

**Issue by mudongliang** [Mooophy/Cpp-Primer#141]
In Ch13 , the Header File need to be arranged ! 
In ex13.1.2.3.cpp , the header file "StrBlob.h" dosen't exist !
And there are the header with  same name , but with a little difference ! 
For example , StrBlob.h , Alan.h
Is there any chance to merge them ? If it can , put the header file in the root dir of ch13.

**Comment by mudongliang** [comment]
And In ch13, there are some error about the way which includes header file :<> , ""!
<> is to find the header file in compile 's standard library !
""  is to find the header file from the current directory!

**Comment by Mooophy** [comment]
You can modify it as you want.

**Comment by mudongliang** [comment]
Who is in charge with this chapter??
Can you explain the dependency of these files in chapter ? I don't know much advanced features of C++ !!

**Comment by Mooophy** [comment]
Sorry @mudongliang  quite busy these days. I'm gonna look into it tomorrow.

**Comment by mudongliang** [comment]
If you are busy , you can let it alone for several days !
I can learn C++ instead ! I think I need to learn some advanced features !

2015-03-03 19:30 GMT+08:00 Yue Wang <notifications@github.com>:

**Comment by Mooophy** [comment]
Sweet, thx for understanding.
