### ISSUE TITLE
ch4 exercise 4.37

### ISSUE THREAD

**Issue by Jtaim** [Mooophy/Cpp-Primer#153]
when I compile with: using GCC 4.9.2 with option -std=c++11
pv = const_cast<string*>(ps);
I get this error:
ex4_37.cpp: In function 'int main()':
ex4_37.cpp:27:33: error: static_cast from type 'const string* {aka const std::basic_string<char>*}' to type 'std::string* {aka std::basic_string<char>*}' casts away qualifiers pv = static_cast<string*>(ps);

pv = static_cast<void*>(const_cast<string*>(ps));
works

**Comment by pezy** [comment]
Hi, @Jtaim Can you paste complete codes?

**Comment by pezy** [comment]
> static_cast from type 'const string* {aka const std::basic_string}' to type '**std::string**

From the error message, I can see you want to convert `const string *` to `string`. But in exercise 4.37, `pv` is `void*`. Thus, following codes work fine:

```cpp
string str("hello");
const string *ps = &str;
void *pv = const_cast<string*>(ps);
// ...
```

And, more exact solution is:

```cpp
pv = static_cast<void*>(const_cast<string*>(ps));
```

So our answer:

> ```
pv = (void*)ps; // pv = const_cast<string*>(ps); or pv = static_cast<void*>(const_cast<string*>(ps));
```

**Comment by Jtaim** [comment]
int main()
{
     using std::string;
    // rewrite each of the following old-style casts to use a named cast:
    // pv = (void*)ps;
    // i = int(*pc);
    // pv = &d;
    // pc = (char*)pv;
    
    int i; double d; const string *ps; char *pc; void *pv;
    
    pv = static_cast<string*>(ps);  // error
    pv = static_cast<void*>(const_cast<string*>(ps));
    i = static_cast<int>(*pc);
    pv = static_cast<void*>(&d);
    pc = reinterpret_cast<char*>(pv);
    return 0;
}

**Comment by Jtaim** [comment]
i see were i went wrong now. used static_cast instead of const_cast.
well i'm still new at this. :)

**Comment by pezy** [comment]
@Jtaim It doesn't matter.

**Comment by Mooophy** [comment]
Hi guys~
If no further discussion needed, please remember to close this issue. 
@Jtaim  @pezy

**Comment by Mooophy** [comment]
thx @Jtaim
