### ISSUE TITLE
source code about ex17.3

### ISSUE THREAD

**Issue by mudongliang** [Mooophy/Cpp-Primer#168]
I try to change the file constructor of chapter 17 , but when I see the directory of ex17.3 , I find that the source code is not complete ! It lacks a header file ! 
Now I will let it alone ! And I will comment it in the makefile !

**Comment by Mooophy** [comment]
I added `#include` into it, please try again.

**Comment by mudongliang** [comment]
Another question about '#include "queryresult.h" '!
where is the queryresult.h file ????
I can't find it in the repo!

**Comment by Mooophy** [comment]
Then ..just leave it alone.

**Comment by mudongliang** [comment]
leave it alone ???? I don't understand!

**Comment by Mooophy** [comment]
I mean.. I don't know as well..

**Comment by mudongliang** [comment]
OK! When I read the book about this question I will try to complete it !
