### ISSUE TITLE
add make usage in README.md in the root directory

### ISSUE THREAD

**Issue by mudongliang** [Mooophy/Cpp-Primer#170]
@Mooophy , I think we should add some simple make usage in README.md in the root directory to help the newer to know how to automake compile our project ! 
How you think it ??

**Comment by Mooophy** [comment]
Agree! @mudongliang

**Comment by Mooophy** [comment]
You can add this stuff into README.md as you want. Just give me a pull request later on. I'm currently working on an experiment at lab. So I'll deal with the other pull request you posted tonight.

**Comment by mudongliang** [comment]
OK , thank you ! I will give you a pull request once I complete it !

**Comment by mudongliang** [comment]
![screenshot from 2015-03-31 19 45 24](https://cloud.githubusercontent.com/assets/6214861/6918231/90fe7838-d7de-11e4-9f0f-8e952a375fad.png)
I don't know much about markdown ! Why are there so many green lines ???
The following is the content I want to add ! @Mooophy , you can write it yourself !

### How to use makefile in linux
    
- make all     : compile all the cpp file to automake object file and executable file !
- make clean   : clean all the object file ! 
- make clobber : clean all the object file and executable file !

Notice ! No matter you are in the root direcotry or in the subdirectory of some chapter , the usage of makefile is the same!

If you know much about make, you can change makefile all by yourself !

**Comment by Mooophy** [comment]
thx
