### ISSUE TITLE
why it is a error?

### ISSUE THREAD

**Issue by mudongliang** [Mooophy/Cpp-Primer#174]
```cpp
class Clock{
	public:
		Clock(int newH = 0, int newM = 0, int newS = 0);
		Clock(Clock &clock);
		Clock(Clock &&clock);
		void setTime(int newH = 0, int newM = 0, int newS = 0);
		void showTime();
		int getHour();
		int getMinute();
		int getSecond();
	private:
		int hour, minute, second;
};
Clock::Clock(int newH, int newM, int newS){
	hour = newH;
	minute = newM;
	second = newS;
	cout<<"call init function!"<<endl;
}
Clock::Clock(Clock &clock){
	hour = clock.hour;
	minute = clock.minute;
	second = clock.second;
	cout<<"call dumplicate init function!"<<endl;
}
bool isAm(Clock c){ //require 24 hour 
	return (c.getHour() < 12);
}
Clock create(){
	Clock c(1,2,3);
	return c;
}
```
-----------------why create function is wrong when I try to call it ??????
@pezy , @Mooophy

**Comment by Mooophy** [comment]
Non-member function `create` was trying to call a move constructor of class `Clock`. As shown in your code, it has not been implemented, which made your compiler upset.

FYI the code below worked on vs2013.

```cpp
#include <iostream>

using namespace std;

class Clock{
public:
	Clock(int newH = 0, int newM = 0, int newS = 0);
	Clock(Clock const &clock);//copy constructor is supposed to use const reference.
	Clock(Clock &&clock)
		: hour(clock.hour), minute(clock.minute), second(clock.second)
	{}
	void setTime(int newH = 0, int newM = 0, int newS = 0)
	{
		hour = newH, minute = newM, second = newS;
	}
	void showTime();
	int getHour() const
	{
		return hour;
	}
	int getMinute() const;
	int getSecond() const;
private:
	int hour, minute, second;
};

Clock::Clock(int newH, int newM, int newS){
	hour = newH;
	minute = newM;
	second = newS;
	cout << "call init function!" << endl;
}

Clock::Clock(Clock const& clock){
	hour = clock.hour;
	minute = clock.minute;
	second = clock.second;
	cout << "call dumplicate init function!" << endl;
}

Clock create(){
	Clock c(1, 2, 3);
	return c;
}

int main()
{
	auto c = create();
	c.setTime();
	cout << c.getHour() << endl;
	system("pause");
}
```
output:
```haskell
call init function!
0
Press any key to continue . . . 
```

**Comment by pezy** [comment]
Second @Mooophy 

IMHO, move constructor shouldn't throw any exceptions, so make it `noexcept`.

**Comment by mudongliang** [comment]
//copy constructor 
    //note : const reference is a must for a copy constructor.
    Clock(Clock const &clock)
        : hour(clock.hour), minute(clock.minute), second(clock.second)
    {}

   I don't understand why i should use const reference !!!!
   Is it a rule ?? Or there are some reasons??????

**Comment by Mooophy** [comment]
@pezy Agree.

**Comment by pezy** [comment]
@mudongliang  You should read <C++ Primer 5th>, and finished all the exercise. :relieved:

**Comment by Mooophy** [comment]
@mudongliang 
It's a rule. Also this rule could be understood this way:
**copy** construtor should not mutate the object passed in， otherwise it's not a **copy**. 
That's why `const &` is a must..

**Comment by mudongliang** [comment]
@pezy I have bought one yesterday! I will read it and finish all the exercise !
Thank you all !

**Comment by mudongliang** [comment]
I have another question that I just thought !!!
when I do not use const as parameter in the copy constructor, though the create function can't be executed , but isAm and "=" can execute successfully and the "call init function!" is there !
Why ???? 
You said we should use const as the parameter ! But when I don't use const , it can be used successfully! @Mooophy @pezy

**Comment by mudongliang** [comment]
I have an idea that the return value is a const , so I can't use a non-const reference value to a const in the copy constructor!
Is it ???? @Mooophy 
Because I just learn C++, I don't know much about the rule ! 
That the parameter must be const in copy constructor may be caused by return schedule! I guess!

**Comment by Mooophy** [comment]
Paste your code please.

**Comment by mudongliang** [comment]
The code just said is in the first block !!!
class Clock{
    public:
        Clock(int newH = 0, int newM = 0, int newS = 0);
        Clock(Clock &clock);
        Clock(Clock &&clock);
        void setTime(int newH = 0, int newM = 0, int newS = 0);
        void showTime();
        int getHour();
        int getMinute();
        int getSecond();
    private:
        int hour, minute, second;
};
Clock::Clock(int newH, int newM, int newS){
    hour = newH;
    minute = newM;
    second = newS;
    cout<<"call init function!"<<endl;
}
Clock::Clock(Clock &clock){
    hour = clock.hour;
    minute = clock.minute;
    second = clock.second;
    cout<<"call dumplicate init function!"<<endl;
}
bool isAm(Clock c){ //require 24 hour 
    return (c.getHour() < 12);
}

**Comment by Mooophy** [comment]
No, the code you pasted does nothing but defines the class `Clock`. I need the complete code that shows how you used this class. Otherwise I can't reproduce the situation you said.

Another suggestion, can you use punctuation other than `!`. It's quite disturbing.

**Comment by pezy** [comment]
I think @mudongliang used `!` to denote his excitement, or just want to give us more and more *surprise!*. just like *Yahoo!* etc. :yum:

**Comment by mudongliang** [comment]
https://github.com/mudongliang/CppLearn/blob/master/clock.cpp
This is the complete code . And I have a understanding of what I ask . 
Maybe It's just a rule . We must follow it .
The compiler only permits us to do this !

**Comment by Mooophy** [comment]
@mudongliang Awesome :+1: 
I believe you are right.

**Comment by mudongliang** [comment]
OK.
