### ISSUE TITLE
Please vote~

### ISSUE THREAD

**Issue by Mooophy** [Mooophy/Cpp-Primer#177]
I'm not sure whether I should merge pull request #175 or not. `makefile` is useful, but it seems a little far away from the content of CP5. So what's your opinion?

Please reply this issue with:
`Yes, merge it.`
Or:
`No, please don't merge it`

I'll count votes in 5 days.Thx for help.

**Comment by Mooophy** [comment]
I'm the first one:

`No, please don't merge it`

**Comment by gtrenching** [comment]
Here is not a project.
```No, please don't merge it.```

**Comment by pezy** [comment]
No, please don't merge it.

**Comment by mudongliang** [comment]
Yes, merge it. I think!

**Comment by Mooophy** [comment]
```cpp
3 : 1
```
@gtrenching  @pezy @mudongliang  
Thx
