### ISSUE TITLE
2.31

### ISSUE THREAD

**Issue by iMinder** [Mooophy/Cpp-Primer#178]
r1 = v2, this is illegal, r1 is normal int & , can not bind to cont int

**Comment by pezy** [comment]
@iMinder `r1 = v2;` It is assigned value to `v1`(which is bind to r1), rather than bind again. You can try it by compiler.

**Comment by Mooophy** [comment]
Agree @pezy 
@iMinder You can look at it like this: After defining `r1`, `r1` becomes another name for variable `v1`, a.k.a aliasing.
So:
```cpp
r1 = v2;
```
is equivalent to :
```cpp
v1 = v2;
``` 
Like @pezy said, this statement has nothing to do with binding.
