### ISSUE TITLE
Ex13.4, the 4th copy constructor

### ISSUE THREAD

**Issue by gtrenching** [Mooophy/Cpp-Primer#180]
Ex13.4 
I really doubt whether this line call the copy constructor or just an assignment.
![image](https://cloud.githubusercontent.com/assets/9496314/7021778/f46affee-dd57-11e4-8852-90e1be04d311.png)

I'm new in C++, looking forward to your answer, thanks  :)

**Comment by pezy** [comment]
@gtrenching copy assignment.

**Comment by Mooophy** [comment]
I tried it like this
```cpp
#include<iostream>

struct Point
{
	Point() = default;

	Point(Point const& other)
	{
		std::cout << "copy ctor\n";
	}

	Point& operator = (Point const& other)
	{
		std::cout << "copy assignment\n";
		return *this;
	}
};


int main()
{
	auto on_heap = new Point();
	Point on_stack;
	*on_heap = on_stack;

	system("pause");
	return 0;
}
```
g++ and vs2013 had the same result:
```
copy assignment
Press any key to continue . . . 
```
Back to the current answer in repo, number 5 should be a copy assignment , no copy constructor being called.

**Comment by Mooophy** [comment]
IMHO, this one is a bug. Thx for reporting @gtrenching

**Comment by Mooophy** [comment]
I did one more experiment  to block synthesized copy assignment operator:
```cpp
#include<iostream>

struct Point
{
	Point() = default;

	Point(Point const& other)
	{
		std::cout << "copy ctor\n";
	}

	Point& operator = (Point const& other);
	//{
	//	std::cout << "copy assignment\n";
	//	return *this;
	//}
};


int main()
{
	auto on_heap = new Point();
	Point on_stack;
	*on_heap = on_stack;

	system("pause");
	return 0;
}
```
Neither g++ or vs2013 compiled, so for such case, only copy assignment operator can be called.

**Comment by culturecircle** [comment]
According to [link](https://stackoverflow.com/questions/29154814/when-is-the-copy-assignment-operator-called)a and my test, `*heap = local` will call copy constructor.

```
Point *heap;
*heap = local; // call copy assignment operator
```
