### ISSUE TITLE
15.2 && 15.16, limit_quote

### ISSUE THREAD

**Issue by CyberLuc** [Mooophy/Cpp-Primer#184]
The exercise description of 15.2 says that:

>Define a class that implements a limited discount strategy, *which applies a discount to books purchased up to a given limit*. If the number of copies exceeds that limit, *the normal price* applies to those purchased *beyongd the limit*.

`double limit_quote::net_price(std::size_t n)` returns `n * price * (n < quantity ? 1 - discount : 1 )`, which should be:
````
double net_price(size_t n) const override {
    if(n <= quantity) return n * price * (1 - discount);
    else return quantity * price * (1 - discount)
            + (n - quantity) * price;
}

````

**Comment by Mooophy** [comment]
Thx for reporting @CyberLuc

**Comment by Mooophy** [comment]
To be fixed in next version.
@pezy

**Comment by pezy** [comment]
@CyberLuc  Agree with you.

But IMHO, `min_qty` should not be ignored. so it should be:

```cpp
if (cnt > max_qty) return max_qty * (1 - discount) * price + (cnt - max_qty) * price;
else if (cnt >= min_qty) return cnt * (1 - discount) * price;
else return cnt * price;
```

How about this?
