### ISSUE TITLE
a few question about make and define protection

### ISSUE THREAD

**Issue by mudongliang** [Mooophy/Cpp-Primer#202]
1. There are some cpp files that have unused variables , may I add "-Wunused-variable" in the compilation selection?
2. About ex11_9_10.cpp file! It is a file to show the error in detail! I can not compile it successfully!
what should I do ? Leave it alone and continue to comment it in makefile Or comment the error lines!

3. About define protection! I think we can obey the [google C++ style](http://google-styleguide.googlecode.com/svn/trunk/cppguide.html#The__define_Guard)
I found there are several kinds of naming types. @pezy

**Comment by Mooophy** [comment]
1, Sure;
2, Leave it alone
3, Sure.
