### ISSUE TITLE
Exercise 7.35 redefine type in class

### ISSUE THREAD

**Issue by boscotsang** [Mooophy/Cpp-Primer#226]
According to page 285, in a class if a member uses a name from an outer scope and that name is type, then the class may not subsequently redefine that name. Some compliers accept this error and I compile  the example code in page 285 with clang++ result in no error.  In Exercise 7.35, in the class the type name Type has been redefined. Shall we still consider redefine the outer type name in class as an error though the compiler accept it?

**Comment by pezy** [comment]
> Shall we still consider redefine the outer type name in class as an error though the compiler accept it?

Yes, I think so.

**Comment by pezy** [comment]
> According to page 285, in a class if a member **uses a name from an outer scope** and that name is type, then the class may not subsequently redefine that name.

In this case, class `Exercise` doesn't use `Type` from outer scope. `typedef double Type;` appears at the beginning of a class. Thus, 

> Shall we still consider redefine the outer type name in class as an error though the compiler accept it?

No, we shouldn't, it's OK.
