### ISSUE TITLE
ex13_42_TextQuery.cpp , What's the difference between "&nos" and "nos"?

### ISSUE THREAD

**Issue by miaojiuchen** [Mooophy/Cpp-Primer#235]
at line 17 , I forgot to write a "&" before nos ,then it occued an access violation error . Could any one helps me with this?

**Comment by miaojiuchen** [comment]
![image](https://cloud.githubusercontent.com/assets/9482138/7453834/f937844a-f29f-11e4-8684-1bd2e497321a.png)

**Comment by miaojiuchen** [comment]
![image](https://cloud.githubusercontent.com/assets/9482138/7453853/2380a948-f2a0-11e4-8921-a74e26c8a177.png)

**Comment by Mooophy** [comment]
@miaojiuchen Nice to meet you.

As a suggestion, please go back to relative sections of CP5 and dive into topics about the Lvalue reference symbol `&`. Without it, it's almost impossible to understand quite a lot of C++ syntax , like Rvalue reference, move semantics, etc.

**Comment by miaojiuchen** [comment]
@Mooophy  Thx very much !  
I think that i could get the meaning of Left value Reference well. (shame
but what i don't understand is that why I can't use the object of a shared_ptr<set<size_t>> itself here but a reference of it, it seems that my code occurred an "Access Violation error" 

take a look at the code below:

①
        string a = "ddd";
	a = "ccc";
	string &aref = a;
	aref = "ccc";
②
        shared_ptr<string> sptr_s = make_shared<string>(new string("ddd"));
	shared_ptr<string> &sptr_s_ref = make_shared<string>(new string("ddd"));
	sptr_s.reset(new string("ccc"));
	sptr_s_ref.reset(new string("ccc"));


what's the difference between them?

**Comment by Mooophy** [comment]
Trust me. As shown in the code above, your c++ skill is quite far away from handling reference together with smart pointer. Go back to the chapters on these topics and write at least 1000 lines of executable c++ codes. After that you can fix such problem within 3 min.

**Comment by miaojiuchen** [comment]
Thx for your comment, i will manage to solve it !
