### ISSUE TITLE
Exercise 7.37

### ISSUE THREAD

**Issue by newhotter** [Mooophy/Cpp-Primer#244]
@Mooophy 
After changing the second constructos to ```Sales_data(const string &s) :bookNo(s){ cout << "aaa" << endl; }``` I test the following code:
```
// Sales_data.cpp
#include "Sales_data.h"


int main()
{
	Sales_data next;
	Sales_data last("3-2-2-22");
	return 0;
}
```
And I found that ```Sales_data next;``` did not call the second constructors.
I think it may called the default constructors.

**Comment by pezy** [comment]
> And I found that Sales_data next; did not call the second constructors.
> I think it may called the default constructors.

Because the `"3-2-2-22"` is [string literal](http://en.cppreference.com/w/cpp/language/string_literal), but your parameter of constructor is `const string &`.

Just try this:

```
#include <string>

int main()
{
    const std::string& s = "hello";
}
```

And back to **2.3.1. References**, review for references.

**Comment by newhotter** [comment]
@pezy 
Thank you for your reply. I  know  that ```Sales_data last("3-2-2-22");``` calls the second parameter.
My point is that ```Sales_data next;``` calls the default constructor but not the second constructor.

**Comment by pezy** [comment]
> My point is that Sales_data next; calls the default constructor but not the second constructor.

same reason. the parameter of second constructor is reference. `Sales_data next;` does not match.

**Comment by pezy** [comment]
default constructor:
```cpp
Sales_data(std::string s = ""): bookNo(s) { }
```

doesn't need parameter. Thus, `Sales_data next;` would call this one.
