### ISSUE TITLE
the problem in Ex11.14

### ISSUE THREAD

**Issue by Soyn** [Mooophy/Cpp-Primer#280]
@Mooophy  Hi,I met some strange problems when I run the code in Ex 11.14.First,why after i input twice "Qq",then we get back to the "lastname", like this:
![1](https://cloud.githubusercontent.com/assets/7734046/8304824/fed579f8-19db-11e5-8850-3520a927735f.png)
And the second problem i think it's a bug,when i want to exit the program.I input the "EOF"(Ctrl + z then enter) on windows and i test in Linux too.They have the same results.Like this:
![2](https://cloud.githubusercontent.com/assets/7734046/8304865/484d5736-19dc-11e5-8822-9e6558abc966.png)
![3](https://cloud.githubusercontent.com/assets/7734046/8304871/503c28be-19dc-11e5-9188-91cb5cfd52af.png)

And it will run untill you close it.
And i can't find a good way to solve these.So if you have a good way.Please @ me.Thx.

**Comment by Mooophy** [comment]
Hi @Soyn 

The code you were using is the first version I did around 2 years ago. I have to say that's quite ugly. So I rewrite it from scratch. You can try the code below. If no more bug found, I'd use this one.

```cpp
#include <iostream>
#include <map>
#include <string>
#include <vector>

using std::ostream; using std::cout; using std::cin; using std::endl; using std::string;
using std::make_pair; using std::pair; using std::vector; using std::map; 

class Families
{
public:
    using Child     = pair<string, string>;
    using Children  = vector<Child>;
    using Data      = map<string, Children>;

    auto add(string const& last_name, string const& first_name, string birthday) -> void
    {
        _data[last_name].push_back(make_pair(first_name, birthday));
    }

    auto print(std::ostream& os) const -> ostream&
    {
        if (_data.empty())
            return os << "No data right now." << endl;

        for (auto const& pair : _data)
        {
            os << pair.first << ":\n" ;
            for (auto const& child : pair.second)
                os << child.first << " " << child.second << endl;
            os << endl;
        }
        return os;
    }

private:
    Data _data;
};

int main()
{
    Families families; 
    string message = "Please enter last name, first name and birthday";
    for (string l, f, b; cout << message << endl, cin >> l >> f >> b; families.add(l, f, b));
    families.print(cout << "Current data:" << endl);

    return 0;
}

Thx.
```

**Comment by Soyn** [comment]
@Mooophy  Hi, i run it on my linux.And it's good thank you.
