### ISSUE TITLE
The free() function of Ex13_49 StrVec and String

### ISSUE THREAD

**Issue by Mugurell** [Mooophy/Cpp-Primer#293]
It's implementation is different from the model presented in the book, 
        
    while(elements != first_free)
        alloc.destroy(--first_free);
versus 
     
    std::for_each(elements, end, [this] (char &c) { alloc.destroy(&c); });

Looks good but I don't think it works as it should.
&nbsp;

To test this:
- Make it public (so that the user can access it), 
- Comment it in the destructor to not be called twice,
- In main create a new object of type String (or StrVec), initializing it with at least one element,
- Check size() (make a new simple one for String if it doesn't exist), call free() and then check size() again.

With the implementation from the book after the call to free() if we check size on that element it says 0,
but with the algorithm implementation after the call to free(), if we call size() we'll get the same size number as before the free().

**Comment by pezy** [comment]
> It's implementation is different from the model presented in the book,
> 
> while(elements != first_free)
>     alloc.destroy(--first_free);

I can't find these codes in the book. Do you mean that:

```cpp
void StrVec::free()
{
    // may not pass deallocate a 0 pointer; if elements is 0, there's no work to do
    if (elements) {
        // destroy the old elements in reverse order
        for (auto p = first_free; p != elements; /* empty */)
            alloc.destroy(--p);
        alloc.deallocate(elements, cap - elements);
    }
}
```

These codes come from 13.5. -> **The free Member** section. IMHO, the codes is almost same as `std::for_each...`'s codes. The `first_free` pointer doesn't really reset too. Cause the `free()` is only used by destructor and assignment operator(copy and move). All of them don't need to reset the `first_free` pointer. (The pointer would be reassigned in assignment operator and doesn't exist after destructor.)

**Comment by Mugurell** [comment]
Yeah, sorry, I was referring to the code you posted.
The while loop implementation was mine and in it I would reset the 'first_free' pointer.

Don't know why but I though this was the way this functions was described in the book.

Your explication makes perfect sense. Thanks for that, and sorry again to trouble you.

**Comment by pezy** [comment]
@Mugurell 

never mind. :smile:
