### ISSUE TITLE
Exercise 13.4

### ISSUE THREAD

**Issue by acgtyrant** [Mooophy/Cpp-Primer#296]
[Exercise 13.4](https://github.com/Mooophy/Cpp-Primer/blob/master/ch13/README.md#exercise-134) note that `Point *heap = new Point(global)` used copy constructor function but`*heap = local` does not.

I think the answer is opposite. The former only initialize a Point object directly and assign a point value to a lvalue. The later dereference a real Point object, and it is assigned.

**Comment by pezy** [comment]
@acgtyrant 

Please check #180 first.

**Comment by acgtyrant** [comment]
Copy.

**Comment by acgtyrant** [comment]
I tried an experiment:

    #include<iostream>

    struct Point {
      Point() {
        std::cout << "default\n";
      }
      Point(Point const& other) {
        std::cout << "copy ctor\n";
      }
      Point& operator = (Point const& other) {
        std::cout << "copy assignment\n";
        return *this;
      }
    };

    Point global;

    void foo_bar() {
      Point *heap = new Point(global);
    }

    int main() {
      foo_bar();
      return 0;
    }

It outputs:

  default
  copy ctor

The C++ Primer says that it will call default constructor when we use `new` to allocate space. But I do not find any place where explains why does copy constructor happens, so do you have any idea? Thank you!

**Comment by Mooophy** [comment]
In which section which part did you read such thing?
>The C++ Primer says that it will call default constructor when we use new to allocate space.

**Comment by acgtyrant** [comment]
@Mooophy 

C++ Primers 5th says that in p458:

> By default, dynamically allocated objects are default initialized (§ 2.2.1, p. 43), which means that objects of built-in or compound type have undefined value; objects of class type are initialized by their default constructor.

**Comment by Mooophy** [comment]
Please notice the term **By default** implying this rule covered **default** situation only.   

Back to your experiment :
```cpp
Point *heap = new Point(global);
```
Since `global` was passed in as an argument, this case has nothing to do with **default**.  In stead, the copy constructor is the perfect match. Thus, compiler will definitely call the copy constructor, rather than anything else.

**Comment by acgtyrant** [comment]
So it is.
