### ISSUE TITLE
Issue with Exercise 13.21

### ISSUE THREAD

**Issue by opensourceDA** [Mooophy/Cpp-Primer#304]
In the answer to Exercise 13.21 it is suggested that the copy constructor of QueryResult class should be declared as deleted. But in the implementation of TextQuery::query function(Exercise 12.32) we use the copy constructor to return a QueryResult type. This results in error. So, the copy constructor for QueryResult class should be deleted.

**Comment by Mooophy** [comment]
Sorry I did't get you.

**Comment by opensourceDA** [comment]
In exercise 13.21 the copy constructor of QueryResult should not be delete. We need the copy constructor in query function of TextQuery class.

**Comment by opensourceDA** [comment]
Exercise 13.21:[link!](https://github.com/Mooophy/Cpp-Primer/tree/master/ch13)
 
    TextQuery(const TextQuery&) = delete;
    TextQuery& operator=(const TextQuery&) = delete;

    QueryResult(const QueryResult&) = delete;    //wrong
    QueryResult& operator=(const QueryResult&) = delete;  //wrong

Reason: 

Need copy constructor here : Exercise 12.32[link!](https://github.com/Mooophy/Cpp-Primer/blob/master/ch12/ex12_32.cpp)

    QueryResult TextQuery::query(const string& str) const 
    {
        // use static just allocate once.
        static shared_ptr<std::set<StrBlob::size_type>> nodate(new std::set<StrBlob::size_type>);
        auto found = result.find(str);
        if (found == result.end()) return QueryResult(str, nodate, input);
        else return QueryResult(str, found->second, input);      //   <--  need copy constructor here
    }

**Comment by pezy** [comment]
> ```cpp
> else return QueryResult(str, found->second, input);      //   <--  need copy constructor here
> ```

why :question:

**Comment by opensourceDA** [comment]
A return is initialized by copy constructor right? Anyway i tried compiling and i got a error so i reported.
I have attached screenshots of the error. Have a look.
![screenshot from 2015-07-23 17 07 55](https://cloud.githubusercontent.com/assets/12014506/8849468/8739c310-315d-11e5-8ab4-82be708ef23d.png)
![screenshot from 2015-07-23 17 07 01](https://cloud.githubusercontent.com/assets/12014506/8849469/8739f5f6-315d-11e5-80b0-0351a098097e.png)

**Comment by Mooophy** [comment]
@opensourceDA 
Which compiler are you using?

**Comment by Mooophy** [comment]
Paste detailed compiler info please.

**Comment by opensourceDA** [comment]
Using g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4 !

**Comment by Mooophy** [comment]
OK. I'll look into it now.

**Comment by opensourceDA** [comment]
Let me know the cause for error whenever u find out please! Thnx

**Comment by Mooophy** [comment]
Please paste the two files you tried to compile, including both the .h and the .cpp file.

**Comment by opensourceDA** [comment]
http://pastebin.com/g6p4uNV5   -- this is the class 

http://pastebin.com/vNCjGAVf    -- driver

**Comment by Mooophy** [comment]
Ok.I think I know what's going on. Basically, we need add one more line into it:
```cpp
QueryResult(QueryResult &&) noexcept = default;
```
For such case, copy constructor works, just as @opensourceDA expected. 
The best match, however, should be move constructor, which has better performance. But the current code has disabled compiler to generate synthesized move constructor for us. So if we want move semantics as expected when copy constructor `delete`ed explicitly, we must explicitly mark the default move constructor with `= default`. 

I tested the code below with VS 2013, Vs 2015 RC and G++ 4.82. All compiled. 
```cpp
#ifndef MY_CLASS
#define MY_CLASS

#include<iostream>
#include<sstream>
#include<fstream>
#include<map>
#include<set>
#include<vector>
#include<string>
#include<memory>

class QueryResult;
std::ostream& print(std::ostream&, const QueryResult&);

class TextQuery {
public:
    //typedef
    using line_no = std::vector<std::string>::size_type;
    //constructor
    TextQuery(std::ifstream&);
    //Query function
    QueryResult query(const std::string&) const;
    TextQuery(const TextQuery&) = delete;
    TextQuery& operator=(const TextQuery&) = delete;
private:
    //data members
    std::shared_ptr<std::vector<std::string>> in_file;
    std::map<std::string, std::shared_ptr<std::set<line_no>>> word_occr;
};

//TextQuery constructor
TextQuery::TextQuery(std::ifstream& input) : in_file(new std::vector<std::string>) {
    for (std::string text; getline(input, text); in_file->push_back(text)) {
        int cur_line_no = in_file->size() + 1;
        std::string word;
        for (std::istringstream line(text); line >> word; ) {
            auto &line_nums = word_occr[word];
            if (!line_nums)
                line_nums.reset(new std::set<TextQuery::line_no>);
            line_nums->insert(cur_line_no);
        }
    }
}

class QueryResult {
    friend std::ostream& print(std::ostream&, const QueryResult&);
public:
    //constructor
    QueryResult(std::string s,
        std::shared_ptr<std::vector<std::string>> f,
        std::shared_ptr<std::set<TextQuery::line_no>> l)
        : sought(s), file(f), lines(l) { }
    QueryResult(const QueryResult&) = delete;
    QueryResult& operator=(const QueryResult&) = delete;



    QueryResult(QueryResult &&) noexcept = default; //!! here!!



    //member functions
    std::set<TextQuery::line_no>::iterator begin() { return lines->begin(); }
    std::set<TextQuery::line_no>::iterator end() { return lines->end(); }
    std::shared_ptr<std::vector<std::string>> get_file() { return file; }
private:
    //data members
    std::string sought;             //word sought by this query
    std::shared_ptr<std::vector<std::string>> file;         //file we are searching in
    std::shared_ptr<std::set<TextQuery::line_no>> lines;    //lines sought is found on
};

QueryResult TextQuery::query(const std::string& s) const {
    static std::shared_ptr<std::set<line_no>> nodata(new std::set<line_no>);
    auto found = word_occr.find(s);
    if (found == word_occr.end())
        return QueryResult(s, in_file, nodata);
    else
        return QueryResult(s, in_file, found->second);
}

std::ostream& print(std::ostream& out, const QueryResult& qr) {
    out << qr.sought << " : " << qr.lines->size() << std::endl;
    return out;
}

#endif
```

Please try it.

**Comment by opensourceDA** [comment]
Yeah, works.

**Comment by Mooophy** [comment]
Thx for reporting.
