### ISSUE TITLE
question on Ex12.1

### ISSUE THREAD

**Issue by xiaodi528** [Mooophy/Cpp-Primer#306]
StrBlob b1;                                  // line1
    {                                                  // line2
        StrBlob b2 = {"a", "an", "the"};// line3
        b1 = b2;                                  // line4
        b2.push_back("about");          // line5
    }                                                  // line6
我得理解是：在第一行，b1的计数是1。第三行，b2的计数是1。第四行，b1在等号左边所以递减，变成0所以销毁了，b2在等号右边所以递增变成2。但答案中b1好像并未被销毁。请我我哪里理解错了？

**Comment by Soyn** [comment]
Plz give an exact exercise the codes  lies in.

**Comment by Soyn** [comment]
You should read the StrBlob carefully, the b1 is the object of StrBlob, not a smart point. The answer by @Mooophy is right.  And read the page 402, the example is similar with ex_12.1.

**Comment by xiaodi528** [comment]
理解了，b1,b2是对象而非智能指针。谢谢

**Comment by Mooophy** [comment]
Hi @xiaodi528 
I think the current answer is quite precise. I'd polish it by rewording. 
Thx for reporting.
