### ISSUE TITLE
a complier error

### ISSUE THREAD

**Issue by Soyn** [Mooophy/Cpp-Primer#307]
`This is the main.cpp` http://pastebin.ca/3073048

`This is the StrVec.h` http://pastebin.ca/3073051

When i build the cpp file. The compiler complains an error: /home/wangyao/C++Primer/CH13/StrVec/main.o:main.cpp|| more undefined references to StrVec::alloc follow|.   And i use the IDE( code::blocks) to compiler my cpp file. The compiler is  `g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2`. 
The exercise is [exercise13.39](https://github.com/Mooophy/Cpp-Primer/blob/master/ch13/ex13_39.cpp).

**Comment by opensourceDA** [comment]
In StrVec.h http://pastebin.ca/3073051 , u made the allocator static. All static members that are constexpr  members must be defined outside the class. If a static member is constexpr it is allowed to be defined and initialised inside the class but never the less it still has to be declared outside the class.

**Comment by Mooophy** [comment]
Sorry.I didn't get you.
Please make sure intent has been stated clearly before pushing any Issue or PR.Otherwise it's gonna be closed.

**Comment by Soyn** [comment]
@opensourceDA  I delete the 'static'. And it works. But i didn't get you. You mean i should declare the static members in class (i.e. declare it in `.h` file)?

**Comment by opensourceDA** [comment]
okay take this example. I have a class Foo which has a static int member, 
    class Foo{
    public: // public members
    private:
        static int x;   //should not give x a value here. Static non-constexpr members cant be defined inside
    };

To make x valid we must define it outside class like this:
    int Foo::x = 20; //Now x takes up the value 20. Note: dont use 'static' qualifier here.
    //static int Foo::x = 20 <-- Wrong 'static' should not be written here

But if ur class is something like this:
    class Foo{
    public: // public members
    private:
        const static int x = 20;   //Since x is constexpr u can give it an in-class initializer
    };

Never the less even if x is constexpr and u have given x an in-class initializer u must declare x outside the class like this:
    const int Foo::x;   // Not declaring x outside is an error

NOTE: Some compilers may allow constexpr static members without the declaration outside the class.

**Comment by Soyn** [comment]
Oh, I get it. THX a lot.
