### ISSUE TITLE
Ex 14.27 doubt 

### ISSUE THREAD

**Issue by opensourceDA** [Mooophy/Cpp-Primer#309]
Why do we pass '-1' as the first argument to check. Isn't it better to pass `curr` ?

    inline StrBlobPtr& StrBlobPtr::operator--()
    {
        --curr;
        check(-1, "decrement past begin of StrBlobPtr");
        return *this;
    }

Even if `curr` is already 0 , after executing `--curr` it will hold a large positive value because it is unsigned type. But, passing a very large value to `check` is bound to throw `out_of_range()` right?

Here is the implementation of check:

    inline shared_ptr<vector<string>> StrBlobPtr::check(size_t i, const string &msg) const
    {
        auto ret = wptr.lock();
        if (!ret) throw std::runtime_error("unbound StrBlobPtr");
        if (i >= ret->size()) throw std::out_of_range(msg);
        return ret;
    }

**Comment by opensourceDA** [comment]
Okay this is useless :X m so stupid anyways closing this issue

**Comment by AntiElephantMine** [comment]
Dunno why you closed this, I think you're right. It should pass curr instead of -1. Passing -1 means it will always throw. It's a mistake in the book I guess?

**Comment by opensourceDA** [comment]
@AntiElephantMine Yeah man  i had so many mixed thoughts on this one. I dont actually remember why i closed this issue. Definitely seems like a mistake in the book.

**Comment by Mooophy** [comment]
fixed in cafddb396ddc4401a0264797d33c871f1d347232
