### ISSUE TITLE
Ex13.27 problem

### ISSUE THREAD

**Issue by xiaodi528** [Mooophy/Cpp-Primer#310]
```cpp    
#include <iostream>
#include <string>
#include <vector>
using namespace std;

class HasPtr {
public:
	HasPtr(const string &s = string()) : ps(new string(s)), i(0), use(new size_t(1)) {}
	HasPtr(const HasPtr &h) : ps(h.ps), i(h.i), use(h.use) { ++*use; }
	HasPtr &operator=(const HasPtr &h)
	{
		++*h.use;
		if (--*use == 0)
		{
			delete ps;
			delete use;
		}
		ps = h.ps;
		i = h.i;
		use = h.use;

		return *this;
	}
	~HasPtr()
	{
		if (--*use == 0)
		{
			delete ps;
			delete use;
		}
	}

	//private:
	string *ps;
	int i;

	size_t *use;
};


int main()
{
	HasPtr h("hi mom");//new
	HasPtr h2 = h;
	HasPtr h3("hi dad");//new
	h2 = h3;

	cout << "h: " << *h.ps << endl;
	cout << "h2: " << *h2.ps << endl;
	cout << "h3: " << *h3.ps << endl;
}
```
**The output is:**
    h: hi mom
    h2: hi dad
    h3: hi dad
**I think the output should be:**
    h: hi dad
    h2: hi dad
    h3: hi dad
**The reason why I think the output should like above:**
h is "hi mom", h2 shares h1, so h2 is "hi mom", h3 is "hi dad", and I think `h2 = h3` changed h1 either because h2 shares h1, but it's not. where am i doing wrong?

**Comment by Mooophy** [comment]
Just confirming, where does this code come from? Is it from this repo?

**Comment by pezy** [comment]
> and I think h2 = h3 changed h1 either because h2 shares h1

What is "share" and HOW ? Could you please elaborate on this?

**Comment by xiaodi528** [comment]
http://stackoverflow.com/questions/31663620/c-copy-control-issue   

I asked on SO. Thanks
