### ISSUE TITLE
Ch15.9 virtual question 

### ISSUE THREAD

**Issue by xiaodi528** [Mooophy/Cpp-Primer#315]
In base class -----  `class Query_base`, two pure virtual functions are private

Then how could his two derived classes:`class WordQuery` and `NotQuery` call this two virtual functions? I think these two virtual functions should be protected, like `class BinaryQuery`.

**Comment by Mooophy** [comment]
>Then how could his two derived classes:class WordQuery and NotQuery call this two virtual functions?

No derived class calls these two functions.
`Virtual` function is super important in C++ learning and quite helpful when moving to other languages that support OO, such as C#, Java, Ruby, Python, etc. So  I think you need go through chapter 15 one more time to find out what's going on. 

Also [this post on SO](http://stackoverflow.com/questions/3970279/what-is-the-point-of-a-private-pure-virtual-function) may be a great read as well.

**Comment by xiaodi528** [comment]
Thank you, very helpful!
