### ISSUE TITLE
EX12.32 use of shared_ptr<StrBlob>

### ISSUE THREAD

**Issue by AntiElephantMine** [Mooophy/Cpp-Primer#318]
Hi, in Ex.12.32 it asks you to use StrBlob instead of vector<string>. I see you then use "shared_ptr< StrBlob > input" in the very literal sense of the question's aim but I think it is unnecessary to declare a shared pointer to a StrBlob. You could just use a StrBlob object without the need to address a shared pointer to it (i.e. "StrBlob input"). This is because StrBlob has an underlying shared pointer to a dynamically allocated vector.

Essentially StrBlob is just a shared_ptr< vector< string > >. Although its purpose is to interface like a container that dynamically allocates its elements, and shares rather than copies those elements when creating other StrBlob objects.

So I think anywhere you have put "shared_ptr< StrBlo b>" should be replaced with "StrBlob" and the functions that use the shared_ptr< StrBlob > changed accordingly.

**Comment by fciasth** [comment]
Thank you for your advice, I will try to modify.

**Comment by fciasth** [comment]
Thank you for your advice, but I didn't write the Ex. 12.32. Would you please look at what you said is which one file?

**Comment by pezy** [comment]
@AntiElephantMine Thx for your suggestion.
