### ISSUE TITLE
Exercise 16.36

### ISSUE THREAD

**Issue by Mugurell** [Mooophy/Cpp-Primer#323]
Your solution
```
 Exercise 16.36:
 What happens in the following calls:
         template <typename T> f1(T, T);
         template <typename T1, typename T2) f2(T1, T2);
         int i = 0, j = 42, *p1 = &i, *p2 = &j;
         const int *cp1 = &i, *cp2 = &j;
             (a) f1(p1, p2);     T is *int
             (b) f2(p1, p2);     T1 and T2 are also *int
             (c) f1(cp1, cp2);   const is ignored
             (d) f2(cp1, cp2);   T1 and T2 are also *int, const is ignored
             (e) f1(p1, cp1);    didn't compile since two types are different int* and const int* respectively
             (f) f2(p1, cp1);    Cp1's const is ignored.
```

I tried testing those functions and seems that the const qualifier is not ignored as you say in the exercise solution.
Here is the output from my program
![templated functions instantiations](https://cloud.githubusercontent.com/assets/11428869/9522914/04dd99fc-4ce0-11e5-9c7d-5551700a5187.png)

Why do you say const is ignored? Can you check?

**Comment by Mooophy** [comment]
You need at least define functions `f1` and `f2` before testing.

**Comment by Mooophy** [comment]
My solution should improve as well. I'd look into it.

**Comment by Mugurell** [comment]
Of course the program will not compile but it shows how the compiler tried to instantiate those functions.
The const qualifier is not ignored.

**Comment by Mooophy** [comment]
You are right. Can you propose a fixed version for this exercise?

**Comment by Mugurell** [comment]
Well, guess you can just update the comments for each example to show how the compiler tries to instantiate each function... 
```
Exercise 16.36:
What happens in the following calls:
         template <typename T> f1(T, T);
         template <typename T1, typename T2) f2(T1, T2);
         int i = 0, j = 42, *p1 = &i, *p2 = &j;
         const int *cp1 = &i, *cp2 = &j;
 f1(p1, p2);     // f1<int*>(int*, int*)
 f2(p1, p2);     // f2<int*, int*>(int*, int*)
 f1(cp1, cp2);   // f1<int const*>(int const*, int const*)
 f2(cp1, cp2);   // f2<int const*, int const*>(int const*, int const*)

 f1(p1, cp1);  // deduced conflicting types for parameter 'T' 
                     // no matching function for call to 'f1(int*&, const int*&)'

 f2(p1, cp1);  // f2<int*, int const*>(int*, int const*)
```

**Comment by Mooophy** [comment]
Thx @Mugurell

**Comment by ijpq** [comment]
`f1(cp1,cp2);` should be `f1<const int*>(const int*, const int*)`, i think
