### ISSUE TITLE
Ex13.49 Message Class

### ISSUE THREAD

**Issue by AntiElephantMine** [Mooophy/Cpp-Primer#328]
Hey, the move operations provided in the Message class do not update the folders to remove the pointers to the moved-from message, nor does it add the pointers to the moved-to message, as it describes to do so in the book. Analogous case for the folder class. There is also no protection against self-assignment in the operator=.

**Comment by Mooophy** [comment]
Quite busy recently, I'd look into it later.

Sorry for that.
