### ISSUE TITLE
Bug in the answer to exercise 14.27

### ISSUE THREAD

**Issue by MrDetective** [Mooophy/Cpp-Primer#336]
Hello,
In the definition of `StrBlobPtr& StrBlobPtr::operator--()`, `check` is called with `-1` as its first argument. Because the first parameter of `check` is a `std::size_t` and `std::size_t` is an unsigned type, so `-1` would be treated as the biggest possible `std::size_t`, which will cause the `check` to always throw (because `-1 >= ret->size()` will always succeed). Indeed, the definition you provided for `StrBlobPtr::operator--()` is identical to the definition provided by the book and I believe it's a bug in the book. I think you should replace `-1` with `curr`.

**Comment by liujshi** [comment]
i think pass curr instead of -1 is right
