### ISSUE TITLE
Ex10_05 may be wrong?

### ISSUE THREAD

**Issue by devilchew** [Mooophy/Cpp-Primer#349]
>@Brief  In the call to equal on rosters, what would happen if both rosters held C-style strings, rather than library strings? 
@Answer For such case, std::equal is going to compare the address value rather than the string value. 
So the result is not the same as std::string. Try to avoid coding this way.
Check #227 for more detail.

In you explanation, "std::equal is going to compare the adress value rather than the string value".But i have test several data, the result of them are same with the variable using std::string. Could you test it once again?

Thanks for your answers which give me great help for learning "C++ Primer".

**Comment by Mooophy** [comment]
Please check #227.

**Comment by devilchew** [comment]
@Mooophy Thanks. Sorry for my oversight.

**Comment by Mooophy** [comment]
All good.
