### ISSUE TITLE
Potential memory leak EX16.28 shared_ptr class.

### ISSUE THREAD

**Issue by AntiElephantMine** [Mooophy/Cpp-Primer#351]
The default constructor:

SharedPointer()
            : ptr{ nullptr }, ref_count{ new std::size_t(1) }, deleter{ cp5::Delete{ } }

And the destructors:

~SharedPointer()
        {
            decrement_and_destroy();
        }

void decrement_and_destroy()
        {
            if (ptr)
            {
                if (0 == --*ref_count)
                {
                    delete ref_count;
                    deleter(ptr);
                }
            }
            ref_count = nullptr;
            ptr = nullptr;
        }

If you default construct a shared_ptr then ptr is nullptr and a new ref_cnt is allocated on the heap. However, when that shared_ptr is destroyed (assuming it was not changed in any way) then ptr will test false in decrement_and_destroy and "delete ref_count" never gets executed.

**Comment by Mooophy** [comment]
Thx.
