### ISSUE TITLE
a quesion from the book (5th )

### ISSUE THREAD

**Issue by RanchoCooper** [Mooophy/Cpp-Primer#355]
in page 490, the function query :
```cpp
if (loc == wm.end)
    ...
else
    return QueryResult(sought, loc->second, file);
```

what's the "loc->second" ???

**Comment by Mooophy** [comment]
Can you list the chapter and section number?

**Comment by RanchoCooper** [comment]
I read the Chinese version, in chapter12
12.3.2  ( definition of TextQuery class  )
in this section there is a part of function `query`

**Comment by pezy** [comment]
@RanchoCooper 

```cpp
map<string, shared_ptr<set<line_no>>> wm;
auto loc = wm.find(sought);
```

> what's the "loc->second" ???

so `loc->second` is `std::shared_ptr<std::set<line_no>>`.

**Comment by RanchoCooper** [comment]
@pezy 
I am a green man :)
maybe I skip over something important before this chapter, which part I though little advanced for me .
does `second` is a member of `std::set` points the second member of the set object ?
if `second` belongs to `set` , why can't I sought it in `cppreference.com`

**Comment by pezy** [comment]
> does second is a member of std::set points the second member of the set object ?

please be careful. `second` is a member of `std::map::iterator`...

see the return type of [`std::map::find`](http://en.cppreference.com/w/cpp/container/map/find)

**Comment by RanchoCooper** [comment]
thx a lot :) 
:+1:
