### ISSUE TITLE
ex13_17_2.cpp doesn't compile

### ISSUE THREAD

**Issue by mustardpower** [Mooophy/Cpp-Primer#366]
When running ex13_17_2.cpp I get:

LNK2001	unresolved external symbol "public: static int numbered::unique" (?unique@numbered@@2HA)	

I think 

    static int unique = 10 

should be

    int numbered::unique = 10

 like in ex13_17_1.cpp.

**Comment by bywend** [comment]
I just want to say, haha

**Comment by mustardpower** [comment]
If only we had a c++ primer...

**Comment by pezy** [comment]
Fixed by #430
