### ISSUE TITLE
Questions about exercise 15.39

### ISSUE THREAD

**Issue by chihyang** [Mooophy/Cpp-Primer#370]
In [exercise 15.39](https://github.com/Mooophy/Cpp-Primer/tree/master/ch15/ex15.39.40), every class is seperated into a header and a source file respectively. Maybe this is intended for learning separate compilation, but seems not a good idea for this exercise. After all, ```OrQuery```, ```AndQuery``` and ```NotQuery``` have no public member functions as interfaces, instead Query is provided as the interface class of them. These "internal" classes should be transparent to user code. But now we have to include these headers in [main.cpp](https://github.com/Mooophy/Cpp-Primer/blob/master/ch15/ex15.39.40/main.cpp), although ```main.cpp``` would never (and can't) use them directly. Would it be better to put ```OrQuery```, ```AndQuery``` and ```NotQuery``` together with ```Query``` in one header and a source file? Thus when we use them, we don't have to worry about any classes as implemention part are left.

**Comment by Mooophy** [comment]
Agree.
Can you implement it as you proposed and give me a pull request?
