### ISSUE TITLE
Question regarding Q2.30 

### ISSUE THREAD

**Issue by hackthehackerman** [Mooophy/Cpp-Primer#380]
The code for Q2.30 is
```
const int v2 = 0; int v1 = v2;
int *p1 = &v1, &r1 = v1;
const int *p2 = &v2, *const p3 = &i, &r2 = v2;
```

The variable i here is not defined in anywhere. Should &i really be &v2?

**Comment by Mooophy** [comment]
I made a check and found that it's exactly the same as what presented in the book. Probably it's a typo made by publisher. I'd remove this part, so that it won't confuse us anymore.

**Comment by hackthehackerman** [comment]
Hi @Mooophy, thank you for your reply. You are right, this is probably a typo. Thank you for double checking it.
