### ISSUE TITLE
ex7.35 的一个疑惑

### ISSUE THREAD

**Issue by huangmingchuan** [Mooophy/Cpp-Primer#390]
## 练习7.35的题目是

> 解释下面代码的含义，说明其中的 Type 和 initVal 分别使用了哪个定义。如果代码存在错误，尝试修改它。
```cpp
typedef string Type;
Type initVal(); 
class Exercise {
public:
    typedef double Type;
    Type setVal(Type);
    Type initVal(); 
private:
    int val;
};
Type Exercise::setVal(Type parm) { 
    val = parm + initVal();     
    return val;
}
```

**在书上255页(中文版)中说**：
> 然而在类中，如果成员使用了外层作用域中的某个名字，而该名字代表一种类型，则类不能在之后重新定义该名字。

而且书上也举了例子
```cpp
typedef double Money;
class Account {
public:
      Money balance() { return bal; } // 使用外层作用域的 Money
private:
      typedef double Money;  // 错误，不能重新定义 Money
      Money bal;
}
```

所以，从这道题来看，代码的错误是不是在于重复定义了 `Type` ?

但是[这里](https://github.com/Mooophy/Cpp-Primer/tree/master/ch07#user-content-exercise-735)的答案和我的想法并不太一样。

**Comment by Mooophy** [comment]
Can you list the section number for page 255?

**Comment by huangmingchuan** [comment]
@Mooophy 
Section 7.4.1
对应英文版 285 页

**Comment by hu895183198** [comment]
事实上，我觉得应该这样解释：
English edition p.285；中文版：255
Tips那里讲的很清楚:Definitions of type names usually should appear at the beginning of a class.
书上给的例子违反了这一原则（说原则可能不太合适？）的，类在定义了函数Account::balance后又定义了一次Money类型别名，编译器不允许这么做。
在例子前的一句话也是这么说的：However, in a class, if a member uses a name from an outer scope and that name is a type, then the class may not 【subsequently redefine】 that name.
回到练习来，练习在定义类的时候立刻redefine了类型别名，在此之前没有使用原类型别名定义类成员，所以不会引发书中示例的错误，只是在定义类内成员函数的时候，编译器不知道如何匹配类内声明的double和类外声明的string。所以由Type Exercise::setVal(Type parm)修改成Exercise::Type Exercise::setVal(Type parm)，指明是类内的Type。

**Comment by vczh** [comment]
Type /*编译器看到这里，当然觉得Type是string*/
Exercise:: /*然后当前scope进入了Exercise*/ 
setVal(Type /*因此这个就是double*/ parm)
/*遇到大括号，发现你声明和定义的函数签名都不一样，报错*/
{ 
    val = parm + initVal();     
    return val;
}

所以要写
Exercise::Type Exercies::setVal(Type parm)

**Comment by huangmingchuan** [comment]
@hu895183198 
@vczh 
谢谢~ 我知道了

**Comment by Mooophy** [comment]
Agree with @vczh . 
It's a great to see you  joined this discussion, welcome.

**Comment by yaomingnew** [comment]
所以重点应该在于类中有没有成员使用过在其前面出现过的类型别名
如果在累的外面定义过类型别名，那么类中使用的就是这个类型别名（此例中是string）
但是在使用过之后如果又重新定义类型别名
那么类中的成员可能就会被这两次定义搞糊涂，到底应该遵循哪次的类型别名定义

**Comment by shen-wanjiang** [comment]
必须要明确的指明该Type类型到底是属于哪个的
`Invalid operands to binary expression ('Exercise::Type' (aka 'double') and 'Type' (aka 'basic_string<char, char_traits<char>, allocator<char>>'))`

**Comment by cegd748** [comment]
我认为答案是对的，首先对外部定义的成员函数用Exercise::Type替换Type很好理解；
      然后我们关注的点是:   initval()是否被重复定义且违反了规则（在类Exercise的内部使用外层作用域全局中的名字initVal，而该名字代表了一种函数类型，则类不能在之后重新定义该名字）。我们要注意的是：类是先处理成员声明再处理成员函数体，则在此例中我们先重复定义了initVal，然后在setVal成员函数体中使用了initVal，即使用前重复定义了initVal,所以没有违反不能使用 后 重复定义的规则；
     最后，因为initval()要代入到运算中，string对象不能自动转换成double类型进行运算，所以initval()的返回值必须可转换成double类型，因此类内部的定义Type initval();是必须的。

**Comment by cegd748** [comment]
我认为答案是对的，首先对外部定义的成员函数用Exercise::Type替换Type很好理解；
      然后我们关注的点是:   initval()是否被重复定义且违反了规则（在类Exercise的内部使用外层作用域全局中的名字initVal，而该名字代表了一种函数类型，则类不能在之后重新定义该名字）。我们要注意的是：类是先处理成员声明再处理成员函数体，则在此例中我们先重复定义了initVal，然后在setVal成员函数体中使用了initVal，即使用前重复定义了initVal,所以没有违反不能使用 后 重复定义的规则；
     最后，因为initval()要代入到运算中，string对象不能自动转换成double类型进行运算，所以initval()的返回值必须可转换成double类型，因此类内部的定义Type initval();是必须的。

**Comment by cegd748** [comment]
我认为答案是对的，首先对外部定义的成员函数用Exercise::Type替换Type很好理解；
      然后我们关注的点是:   initval()是否被重复定义且违反了规则（在类Exercise的内部使用外层作用域全局中的名字
initVal，而该名字代表了一种函数类型，则类不能在之后重新定义该名字）。我们要注意的是：类是先处理成员声明再
处理成员函数体，则在此例中我们先重复定义了initVal，然后在setVal成员函数体中使用了initVal，即使用前重复定义了
initVal,所以没有违反不能使用 后 重复定义的规则；
     最后，因为initval()要代入到运算中，string对象不能自动转换成double类型进行运算，所以initval()的返回值必须可转换成double类型，因此类内部的定义Type initval();是必须的。

**Comment by cegd748** [comment]
1.我认为答案是对的，首先对外部定义的成员函数用Exercise::Type替换Type很好理解；

2.然后我们关注的点是:   initval()是否被重复定义且违反了规则（在类Exercise的内部使用外层作用域全局中的名字
initVal，而该名字代表了一种函数类型，则类不能在之后重新定义该名字）。我们要注意的是：类是先处理成员声明再
处理成员函数体，则在此例中我们先重复定义了initVal，然后在setVal成员函数体中使用了initVal，即使用前重复定义了
initVal,所以没有违反不能使用 后 重复定义的规则；

3.最后，因为initval()要代入到运算中，string对象不能自动转换成double类型进行运算，所以initval()的返回值必须可转换成double类型，因此类内部的定义Type initval();是必须的。

**Comment by cegd748** [comment]
1.我认为答案是对的，首先对类外部定义的成员函数Exercise::Type替换Type很好理解；

2.然后我们关注的一点是：initval()是否被重新定义并且违反了规则（在类Exercise的内部使用外部作用域全局中的名字initVal，而该名字代表了一种函数类型，则类不能在其后重定义该名字）。我们要注意的是：定义类是先处理成员声明再处理成员函数，则在此例中我们先重复定义了initVal，然后在setVal成员函数中使用了initVal，即使用前重新定义了initVal,所以没有违反不能使用后重新定义的规则；

3.最后，因为initval()要代入到运算中，string对象不能自动转换成double类型进行运算，所以initval()的返回值必须可转换成double类型，因此类内部的定义Type initval();是必须的。
