### ISSUE TITLE
the answer about ch08 ex8.12

### ISSUE THREAD

**Issue by bjut-hz** [Mooophy/Cpp-Primer#401]
I have tested in-class initializers as follows:
```
struct PersonInfo{
	string name = "init";
	vector<string> phones {"10","2"};
};

int main(){
	PersonInfo person;
	cout << person.name;

	system( "pause" );
}
```
It will cause an error：
![](http://i.imgur.com/x9pRdC1.png error)

But it will be ok if I write as follows:
```
struct PersonInfo{
	string name = "init";
	vector<int> phones {10,2};
};
```
I don't know why, can someone else tell me?

In addition, why can't a a aggregate class have in-class initializers.

**Comment by pezy** [comment]
It seem a bug of Visual studio compiler. The code works well with gcc/clang.

Have a look at : http://cpp.sh/8pm7k.

**Comment by wtlusvm** [comment]
It seems that Microsoft has fixed this "bug"(I am not quite sure if it is) at the latest version of VS(Visual Studio 2015 with Update 1). It works on my laptop.

**Comment by bjut-hz** [comment]
Many thanks~ @wtlusvm @pezy
