### ISSUE TITLE
Wrong example (§12.3, p.484)

### ISSUE THREAD

**Issue by bjut-hz** [Mooophy/Cpp-Primer#406]
I think the Text-Query program can't solve problem raised in §12.3. It does print the number of line which contains specific word not the number of times the word occur. It is a bug in the book.

**Comment by pezy** [comment]
> Our program will let a user search a given file for words that might occur in
it. **The result of a query will be the number of times the word occurs and a list of lines
on which that word appears**. If a word occurs more than once on the same line, we’ll
display that line **only once**. Lines will be displayed in **ascending order**—that is, line 7
should be displayed before line 9, and so on.

Any questions?

**Comment by bjut-hz** [comment]
I did not express well. You can see the code in the book(§12.3, p490).
```
os << qr.sought << " occurs " << qr.lines->size() << " " << make_plural( qr.lines->size(), "time", "s" ) << endl; 
```
The `qr->lines` is `set` type. The code print the number of times of line not the number of times the word occurs.

**Comment by pezy** [comment]
Why don't you see the following code?

```cpp
// print each line in which the word appeared
for (auto num : *qr.lines) // for every element in the set
    // don't confound the user with text lines starting at 0
    os << "\t(line " << num + 1 << ") " << *(qr.file->begin() + num) << endl;
```

**Comment by bjut-hz** [comment]
Ah, I have run the code. The result is as follow:
![result](http://i.imgur.com/KO8wGSL.png "result")
The input data is:
```
element element
a element
```
Is not the number should be 3? That is to say the program should print as follows:
```
element occurs 3 times
```

**Comment by pezy** [comment]
eh... I finally understand what you mean. And I have to admit that this was indeed a bug... sorry for the delayed response.

Maybe we should use `std::multiset` instead of `std::set`?

**Comment by bjut-hz** [comment]
Sorry for the delayed response. Agree with you that we should  use `std::multiset` instead of `std::set`.
