### ISSUE TITLE
Could you post the code of "Sales_item.h"? where is that? thanks

### ISSUE THREAD

**Issue by shiyilin890** [Mooophy/Cpp-Primer#407]

**Comment by pezy** [comment]
Just in the repo: https://github.com/Mooophy/Cpp-Primer/blob/master/include/Sales_item.h

**Comment by shiyilin890** [comment]
Thanks for the quick response! How to download this? If I copy this (or any solution you posted), it will take the number ahead of each line, it is tedious to delete the numbers one by one. （这个网站帮助真大！没想到是中国人办的，请教怎么把程序从你们的网页复制到txt里呢？我直接粘贴的话，每行前面都会有那个代表行号的数字，一个个删太麻烦了，谢谢！）

**Comment by pezy** [comment]
> If I copy this (or any solution you posted), it will take the number ahead of each line, it is tedious to delete the numbers one by one.

![image](https://cloud.githubusercontent.com/assets/1147451/13735957/c418f62a-e9ea-11e5-9a59-db36c2085cd0.png)

clicked `Raw`, and then copy it more easily.

> 这个网站帮助真大！没想到是中国人办的，请教怎么把程序从你们的网页复制到txt里呢？我直接粘贴的话，每行前面都会有那个代表行号的数字，一个个删太麻烦了，谢谢！

这个网站是 Github 的。简介在这里：https://github.com/about
如果有使用上的疑惑，在这里查询：https://help.github.com/

**Comment by yangxuyu** [comment]
thanks
