### ISSUE TITLE
Discussions for Ex 7.54

### ISSUE THREAD

**Issue by ArtanisCV** [Mooophy/Cpp-Primer#435]
Ex 7.54: 

> Should the members of Debug that begin with set_ be declared as constexpr? If not, why not?

The current answer is:

> shouldn't, cause a constexpr function must contain exactly one return statement.

I think this is not the real reason. Note that, for a function returning void, you can always use static_cast to drop unwanted results:
`void set_io(bool b) { return static_cast<void>(io = b); }`

In my opinion, the real problem is that, in C++11, constexpr member functions are implicitly const, so the "set_xx" functions, which will modify data members, cannot be declared as constexpr. In C++14, this property no longer holds, so constexpr is suitable.

**Comment by pezy** [comment]
Agree with you.
