### ISSUE TITLE
Why the function I defined do not work?

### ISSUE THREAD

**Issue by mikeGDS** [Mooophy/Cpp-Primer#477]
```cpp
void copy_value_to_deq(list<int>st, deque<int>deq1,deque<int>deq2)
{
	for (const auto& c : st){
		if (c % 2 == 0)
			deq2.push_back(c); 
		else
			deq1.push_back(c);
	}
}
int main()
{
	deque<int>dq1;
	deque<int>dq2;
	list<int> ist= {1,2,3,4,5,6,7,8,9,0};
	copy_value_to_deq(ist, dq1, dq2);
	for (const auto& i:dq1) {cout << i << " ";}
	return 0;
}
```

 I defined copy_value_to_deq() in order to get odd value from the list.However,there was no output in the screen.It seems like the function doesn't play a role in the program.
  I  am appreciated anyone for answering my question!

**Comment by pezy** [comment]
change
```cpp
void copy_value_to_deq(list<int>st, deque<int>deq1,deque<int>deq2)
```
to
```cpp
void copy_value_to_deq(list<int> st, deque<int>& deq1,deque<int>& deq2)
```

**Comment by mikeGDS** [comment]
Thank you for answering ! The function called by reference(parameter passed by reference) can change the argument(dq1,dq2).I  realize that it is a stupid question as I didn't think it carefully.
  All the  best in your work!
