### ISSUE TITLE
9.48 wrong answer

### ISSUE THREAD

**Issue by jenenliu** [Mooophy/Cpp-Primer#484]
`numbers = "0123456789"
 name = "r2d2";
 numbers.find_first_of(name);`

should return 2, not string::npos

**Comment by pezy** [comment]
> numbers.find_first_of(name);

The question ask `numbers.find(name);` rather than `numbers.find_first_of(name);`.

check: http://coliru.stacked-crooked.com/a/9ec19116b8f89c7d

**Comment by jenenliu** [comment]
my bad, thanks
2016年6月23日 下午5:40，"pezy" <notifications@github.com>写道：
