### ISSUE TITLE
Exercise 2.31

### ISSUE THREAD

**Issue by rcompass** [Mooophy/Cpp-Primer#494]
Hi mate. Your solutions are excellent. The answer to Exercise 2.31.a is incorrect though.

r1 = v2. This is illegal. 

Cheers.

**Comment by foxtrot9** [comment]
Yes, @rcompass you are right. Solution is wrong in repo.
``r1 = v2 // It is wrong because int reference cannot point to const int.``

`` Compiler error: invalid initialization of reference of type ‘int&’ from expression of type ‘const int’ ``

```
usr@ubuntu14:~/test$ cat 7.cpp
#include <iostream>
int main()
{
	const int v2 = 0;
	int v1 = v2;
	int *p1 = &v1, &r1 = v2;
	return 0;
}
usr@ubuntu14:~/test$ g++ -std=c++11 7.cpp
7.cpp: In function ‘int main()’:
7.cpp:6:23: error: invalid initialization of reference of type ‘int&’ from expression of type ‘const int’
  int *p1 = &v1, &r1 = v2;
                                  ^
```

**Comment by ZhangZhenghao** [comment]
Hi, @rcompass and @foxtrot9. Actually, r1 = v2 is legal.
Because r1 = v2 is doing assignment not binding. Test code should be written like this:
```c++
#include <iostream>
int main()
{
    const int v2 = 0;
    int v1 = v2;
    int *p1 = &v1, &r1 = v1;
    r1 = v2;
    return 0;
}
```

**Comment by rcompass** [comment]
Yes. For your code snippet you're correct, Zhenghao.

**Comment by zzhhbyt1** [comment]
@rcompass Thanks for your contribution and if this solved your question you can close this issue manually.
