### ISSUE TITLE
ex. 6.45 Typo

### ISSUE THREAD

**Issue by fllprbt** [Mooophy/Cpp-Primer#523]
For example, the function arrPtr in Exercise 6.38 and make_plural in Exercise 6.42 should be defined as inline. But the function func in Exercise 6.4 shouldn't. ~~Cause it just being call once and too many codes in the function.~~ It is not that small and its being called once. Hence, it will probably not expand as inline.

**Comment by RobRoyce** [comment]
Thank you! I went ahead and submitted the updates.
