### ISSUE TITLE
ex 11.4

### ISSUE THREAD

**Issue by YiFangxin** [Mooophy/Cpp-Primer#554]
error : no matching function for call  to 'remove_if'

std::
template <class charT>
  bool ispunct (charT c, const locale& loc);

remove_if(beg,end,pred)   this is a unary predicate.

`
remove_if(str.begin(),str.end(),[](char c){return ispunct(c);});
`
Wanted to know if it's right？ @pezy

**Comment by wtlusvm** [comment]
Can't reproduce. `g++ (Debian 4.9.2-10) 4.9.2` return no errors. Plz re-check your compiler.

**Comment by YiFangxin** [comment]
i am clear now.
the reason might be that i code `using namespace std` in begining.
then,it might be use std::ispunct by default.
