### ISSUE TITLE
wrong answer in 2.29 (b)

### ISSUE THREAD

**Issue by andy-qiu1** [Mooophy/Cpp-Primer#566]
Your answer is: 
p1 = p3;    // illegal. p3 is a pointer to const int.

but I think the correct answer is:
p1 = p3;    // legal. p3 is a constant pointer to const int, and p1 is a pointer to const int.  It is possible to change the value of p1 to p3 because p1 is not a const pointer.

**Comment by pezy** [comment]
please check: http://www.cpp.sh/6ok5

**Comment by andy-qiu1** [comment]
Thank you for your answer.  I understand my mistake now.
