### ISSUE TITLE
Exercise 13.43 no need to capture this

### ISSUE THREAD

**Issue by gzc1003** [Mooophy/Cpp-Primer#570]
`for_each(elements, first_free, [](std::string &rhs){ alloc.destroy(&rhs); });`

Because `alloc` is a class static member, not bound to `this`, lambda can use it directly, no need to capture `this`. 

Or to say, `alloc` is "visible" not caused by capturing `this`.

**Comment by pezy** [comment]
> Because alloc is a class static member

why? the `alloc` isn't static member in book.

check: 13.5 Classes That Manage Dynamic Memory | **StrVec Class Definition**

**Comment by gzc1003** [comment]
Oh, I see.  In English version `alloc` isn't a static member, but in Chinese version(*C++ primer* 5th) it's.

![13 5](https://user-images.githubusercontent.com/16793045/27744485-3f47cf66-5df2-11e7-95a1-e20e7ce1d311.PNG)
