### ISSUE TITLE
Exercise 10.21's solution allows decrementing even after the captured value reaches to 0

### ISSUE THREAD

**Issue by agyild** [Mooophy/Cpp-Primer#620]
Exercise 10.21 is as follows:
>Write a lambda that captures a local int variable and decrements that variable until it reaches 0. **Once the variable is 0 additional calls should no longer decrement the variable.** The lambda should return a bool that indicates whether the captured variable is 0.

The given solution (https://www.ideone.com/SA5oeQ),
```c++
auto check_and_decrement = [&i](){ return --i ? false : true; };
```

It doesn't do any sanity checking for the initial value and subsequent calls, if i is initialized as 0 at local scope it decrements it to -1 and returns false.

I propose an alternative better lambda function (https://www.ideone.com/hcX6gP):
```c++
auto check_and_decrement = [&i]() { return i > 0 ? !--i : !i; };
```
1. It only returns true if the captured value is 0
2. It only decrements if the captured value is greater than 0

I have also considered if I should be checking the initial state of the captured value by using a post-increment operator or using a temporary value but came to the conclusion it is actually better to check the processed value since it allows the caller to know once the captured value has reached zero.

**Comment by pezy** [comment]
Awesome! Could you please send a pull request for this improving? I am very happy to merge it.

**Comment by agyild** [comment]
@pezy Done. https://github.com/Mooophy/Cpp-Primer/pull/624
