### ISSUE TITLE
5.4 b 没有意义

### ISSUE THREAD

**Issue by sw5cc** [Mooophy/Cpp-Primer#644]
```
//corrrected as:
while (bool status = find(word)) { 
    /* ... */ 
    if (!status) { /* ... */ }
}
```
这个status如果为false则不会进入循环

**Comment by pezy** [comment]
@sw5cc 方便发一个 pull request 修复它吗?

**Comment by sw5cc** [comment]
嗯，可以 @pezy

**Comment by CnrBeili** [comment]
这是肯定的

发自我的 iPhone

在 2018年4月8日，下午7:13，sw5cc <notifications@github.com<mailto:notifications@github.com>> 写道：


Closed #644<https://github.com/Mooophy/Cpp-Primer/issues/644>.
