### ISSUE TITLE
3.26 should be improved

### ISSUE THREAD

**Issue by myk502** [Mooophy/Cpp-Primer#652]
The correct answer should be:
when beg and end are both large enough, adding beg and end together will cause overflow, while 'mid = (beg + (end - beg) / 2)' will not

**Comment by pezy** [comment]
> when beg and end are both large enough, adding beg and end together will cause overflow

what your mean that "beg and end are both large enough"? what's the point that the result of any iterator added with `end`?

**Comment by Hierom** [comment]
The main reason is it can't add `+` iterators to each other or divide `/` iterators by some value.
