### ISSUE TITLE
About Chapter 6 Exercise6.48

### ISSUE THREAD

**Issue by myk502** [Mooophy/Cpp-Primer#657]
I think in Exercise 6.48, 
`assert(cin)` is equivlant to `assert(s == sought)`, for the following reasons:
when control flow comes to the assert statement, the while loop condition check must failed:
if (cin >> s) failed, that means in the previous while loop, s != sought, so The assert failure is correct here
if(s != sought) failed, then s == sought, the assert does not fail(for the short circuit operator &&), which is also correct here

**Comment by pezy** [comment]
check `cin` is meanless here. Depends on the program logic, it is want to ensure that after the loop, `s` should be equivlant to `sought`. so it make more sense to write `assert(s == sought)`.

**Comment by myk502** [comment]
Closing old issues
