### ISSUE TITLE
About Exercise 7.13

### ISSUE THREAD

**Issue by myk502** [Mooophy/Cpp-Primer#658]
at line 10, add a condition statement
`if(!is)
     break;`
will make the program better, which deals with the last input and avoid the meaningless"0 0 0" output.

**Comment by pezy** [comment]
@myk502 

Sorry, you mean add the statement at here?

https://github.com/Mooophy/Cpp-Primer/blob/master/ch07/ex7_13.cpp#L10

and I cannot get the "0 0 0" output, could you please show the sequences of the inputs?

**Comment by myk502** [comment]
Sorry about the line 10, because that was on my own editor. My new version of ex7_13 is as below:
`//
//  ex7_13.cpp
//  Exercise 7.13
//
//  Created by pezy on 11/9/14.
//

#include "Sales_data.h"

int main()
{
    Sales_data total(std::cin);
    if (!total.isbn().empty())
    {
        std::istream &is = std::cin;
        while (is) {
            Sales_data trans(is);
			if(!is)
				break;
            if (total.isbn() == trans.isbn())
                total.combine(trans);
            else {
                print(std::cout, total) << std::endl;
                total = trans;
            }
        }
        print(std::cout, total) << std::endl;
    }
    else
    {
        std::cerr << "No data?!" << std::endl;
        return -1;
    }
    
    return 0;
}
`
And the meaningless output occurs when you want to end your input by typing a ctrl + D(unix) or ctrl + z(windows) for Simulation of EOF; or in the case when you read redirection.

**Comment by pezy** [comment]
Ok, I see the " 0 0" output at last.

But added your statement, it still output that... Can you check about that ?

**Comment by myk502** [comment]
```
//
//  ex7_13.cpp
//  Exercise 7.13
//
//  Created by pezy on 11/9/14.
//

#include "Sales_data.h"

int main()
{
    Sales_data total(std::cin);
    if (!total.isbn().empty())
    {
        std::istream &is = std::cin;
        while (is) {
            Sales_data trans(is);
			if(!is)
				break;
            if (total.isbn() == trans.isbn())
                total.combine(trans);
            else {
                print(std::cout, total) << std::endl;
                total = trans;
            }
        }
        print(std::cout, total) << std::endl;
    }
    else
    {
        std::cerr << "No data?!" << std::endl;
        return -1;
    }
    
    return 0;
}

```
This is my version, only changed the name of header file to "Sales_data.h"

**Comment by pezy** [comment]
I got it,  thanks for your contribute. 💯
